Document: flexswitch
Title: Debian flexswitch Manual
Author: <insert document author here>
Abstract: This manual describes what flexswitch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flexswitch/flexswitch.sgml.gz

Format: postscript
Files: /usr/share/doc/flexswitch/flexswitch.ps.gz

Format: text
Files: /usr/share/doc/flexswitch/flexswitch.text.gz

Format: HTML
Index: /usr/share/doc/flexswitch/html/index.html
Files: /usr/share/doc/flexswitch/html/*.html
