#!/usr/bin/env python
import os
import sys
import time
import daemon 
from optparse import OptionParser

def getDaemonsInfo (baseDir) :

    daemonsToStart = [
                    {'name': 'asicd',
                     'params': '-params=' + baseDir + '/params'},

                    {'name': 'arpd',
                     'params': '-params=' + baseDir + '/params'},

                    {'name': 'portd',
                     'params': '-params=' + baseDir + '/params'},

                    {'name': 'ribd',
                     'params': '-params=' + baseDir + '/params'},

                    {'name': 'bgpd',
                     'params': '-params=' + baseDir + '/params'},

                    {'name': 'confd',
                    'params': '-params=' + baseDir + '/params'},
                    ]
    return daemonsToStart

class FlexSwitchDaemon (daemon.Daemon):
    def run(self, *args, **kwargs):
        print "Running ConfD"
        cmd = args[0][0]
        pargs = args[0]
        os.execvp(cmd, pargs)


if __name__=="__main__":
    parser = OptionParser()

    parser.add_option("-d", "--dir", 
                      dest="directory",
                      action='store',
                      help="Directory where the binaries are stored")

    (opts, args) = parser.parse_args()
    baseDir = opts.directory if (opts.directory != None) else "/opt/flexswitch"
    pidFileDir = baseDir+'/bin/pids/'

    if not os.path.exists(pidFileDir):
        os.makedirs(pidFileDir)

    for dmn in getDaemonsInfo(baseDir+'/bin'): 
        print "Starting Daemon %s" %( dmn['name'])
        cmd = baseDir +'/bin/'+ dmn['name'] 
        pargs = (cmd, dmn['params'])
        pidFile = pidFileDir + dmn['name']+'.pid' 
        print 'PID File is %s' %(pidFile)
        dmn = FlexSwitchDaemon (pidFile, 
                                stdout= baseDir+'/bin/'+'log.txt', 
                                stderr= baseDir+'/bin/'+'log.txt', 
                                verbose=2)
        dmn.start(pargs)
